#!/usr/bin/env bash

## Copyright (C) 2020-2026 Aditya Shakya <adi1090x@gmail.com>

# i3 directory
DIR="$HOME/.config/i3"

# Launch dunst daemon
if [[ $(pidof dunst) ]]; then
	pkill dunst
fi

if [[ -f "$HOME/.config/dunst/dunstrc" ]]; then
	dunst &
else
	dunst -config "$DIR"/dunstrc &
fi
