#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/i3"
RASI="$DIR/theme/rofi/screenshot.rasi"

# Theme Elements
prompt='Screenshot/Flameshot'
mesg="Directory :: $(xdg-user-dir PICTURES)/Screenshots"

# Options
layout=$(cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2)
if [[ "$layout" == 'NO' ]]; then
  option_1=" Capture Desktop"
  option_2=" Capture Area"
  option_3=" Capture Window"
  option_4=" Capture in 5s"
  option_5=" Capture in 10s"
else
  option_1=""
  option_2=""
  option_3=""
  option_4=""
  option_5=""
fi

# Rofi CMD
rofi_cmd() {
  rofi -dmenu \
    -p "$prompt" \
    -mesg "$mesg" \
    -markup-rows \
    -theme ${RASI}
}

# Pass variables to rofi dmenu
run_rofi() {
  echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5" | rofi_cmd
}

# Actions
chosen="$(run_rofi)"
echo "$chosen"
case ${chosen} in
$option_1)
  echo "EXEC 1"
  bash "$DIR"/scripts/i3_flameshot --now
  ;;
$option_2)
  echo "EXEC 2"
  bash "$DIR"/scripts/i3_flameshot --area
  ;;
$option_3)
  echo "EXEC 3"
  bash "$DIR"/scripts/i3_flameshot --win
  ;;
$option_4)
  echo "EXEC 4"
  bash "$DIR"/scripts/i3_flameshot --in5
  ;;
$option_5)
  echo "EXEC 5"
  bash "$DIR"/scripts/i3_flameshot --in10
  ;;
esac
