#!/usr/bin/env bash

## Copyright (C) 2020-2026 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/i3"
RASI="$DIR/theme/rofi/launcher.rasi"

# Run
rofi \
    -show drun \
    -kb-cancel Escape,Super+F1,Alt-F1 \
    -theme ${RASI}
