#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/i3"
RASI="$DIR/theme/rofi/clipboard.rasi"

# Run
rofi \
	-kb-cancel Super+v,Alt-F1,Escape \
	-theme ${RASI} \
    -modi "clipboard:greenclip print" -show clipboard
