# "everforest"
[color]

BACKGROUND = #2d353b
FOREGROUND = #d3c6aa
ALTBACKGROUND = #343f44
ALTFOREGROUND = #859289
ACCENT = #e69875

BLACK = #2d353b
RED = #e67e80
GREEN = #a7c080
YELLOW = #dbbc7f
BLUE = #7fbbb3
MAGENTA = #d699b6
CYAN = #83c092
WHITE = #d3c6aa
ALTBLACK = #7a8478
ALTRED = #e67e80
ALTGREEN = #a7c080
ALTYELLOW = #dbbc7f
ALTBLUE = #7fbbb3
ALTMAGENTA = #d699b6
ALTCYAN = #83c092
ALTWHITE = #d3c6aa
