# "everforest"
[urgency_low]
  timeout = 2
  background = "#2d353b"
  foreground = "#d3c6aa"
  frame_color = "#e69875"

[urgency_normal]
  timeout = 5
  background = "#2d353b"
  foreground = "#d3c6aa"
  frame_color = "#e69875"

[urgency_critical]
  timeout = 0
  background = "#2d353b"
  foreground = "#e67e80"
  frame_color = "#e67e80"
