# "everforest"
set $i3_cl_col_bg #2d353b
set $i3_cl_col_fg #d3c6aa
set $i3_cl_col_in #a7c080
set $i3_cl_col_afoc #e69875
set $i3_cl_col_ifoc #7fbbb3
set $i3_cl_col_ufoc #343f44
set $i3_cl_col_urgt #d699b6
set $i3_cl_col_phol #2d353b
